-- Phase 2 seed/reference data for local development.
-- Production faculty/program, onboarding taxonomy, and matching configuration
-- are tracked in migrations, not seeded here.
-- Do not seed guessed corporate email domains here.
